### ISSUE TITLE
Can rocky acess tms service provided by geoserver

### ISSUE THREAD

**Issue by wwwronin** [pelicanmapping/rocky#12]
Hi,
 I try tms image layer  provided by geoserver in rocky and URL like this:
"http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Aspt_15@EPSG%3A4326@png/"
but returned error: Failed to establish a profile for "http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Aspt_15@EPSG%3A4326@png/"

**Comment by gwaldron** [comment]
What does the TMS tilemap look like?
Open that URL in your browser and post the XML here.

If you know the profile is global-geodetic or spherical-mercator, you can tell rocky:
```c++
layer->setProfile(rocky::Profile::GLOBAL_GEODETIC);
```

**Comment by wwwronin** [comment]
<TileMap version="1.0.0" tilemapservice="http://localhost:10086/geoserver/gwc/service/tms/1.0.0">
<Title>Aspt_15</Title>
<Abstract/>
<SRS>EPSG:4326</SRS>
<BoundingBox minx="90.0" miny="0.0" maxx="135.0" maxy="45.0"/>
<Origin x="90.0" y="0.0"/>
<TileFormat width="256" height="256" mime-type="image/png" extension="png"/>
<TileSets profile="local">
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/1" units-per-pixel="0.3515625" order="0"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/2" units-per-pixel="0.17578125" order="1"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/3" units-per-pixel="0.087890625" order="2"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/4" units-per-pixel="0.0439453125" order="3"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/5" units-per-pixel="0.02197265625" order="4"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/6" units-per-pixel="0.010986328125" order="5"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/7" units-per-pixel="0.0054931640625" order="6"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/8" units-per-pixel="0.00274658203125" order="7"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/9" units-per-pixel="0.001373291015625" order="8"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/10" units-per-pixel="6.866455078125E-4" order="9"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/11" units-per-pixel="3.4332275390625E-4" order="10"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/12" units-per-pixel="1.71661376953125E-4" order="11"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/13" units-per-pixel="8.58306884765625E-5" order="12"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/14" units-per-pixel="4.291534423828125E-5" order="13"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/15" units-per-pixel="2.1457672119140625E-5" order="14"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/16" units-per-pixel="1.0728836059570312E-5" order="15"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/17" units-per-pixel="5.364418029785156E-6" order="16"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/18" units-per-pixel="2.682209014892578E-6" order="17"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/19" units-per-pixel="1.341104507446289E-6" order="18"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/20" units-per-pixel="6.705522537231445E-7" order="19"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/21" units-per-pixel="3.3527612686157227E-7" order="20"/>
</TileSets>
</TileMap>

**Comment by wwwronin** [comment]
<TileMap version="1.0.0" tilemapservice="http://localhost:10086/geoserver/gwc/service/tms/1.0.0">
<Title>zbaa_15</Title>
<Abstract/>
<SRS>EPSG:4326</SRS>
<BoundingBox minx="90.0" miny="0.0" maxx="135.0" maxy="45.0"/>
<Origin x="90.0" y="0.0"/>
<TileFormat width="256" height="256" mime-type="image/png" extension="png"/>
<TileSets profile="local">
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/1" units-per-pixel="0.3515625" order="0"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/2" units-per-pixel="0.17578125" order="1"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/3" units-per-pixel="0.087890625" order="2"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/4" units-per-pixel="0.0439453125" order="3"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/5" units-per-pixel="0.02197265625" order="4"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/6" units-per-pixel="0.010986328125" order="5"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/7" units-per-pixel="0.0054931640625" order="6"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/8" units-per-pixel="0.00274658203125" order="7"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/9" units-per-pixel="0.001373291015625" order="8"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/10" units-per-pixel="6.866455078125E-4" order="9"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/11" units-per-pixel="3.4332275390625E-4" order="10"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/12" units-per-pixel="1.71661376953125E-4" order="11"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/13" units-per-pixel="8.58306884765625E-5" order="12"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/14" units-per-pixel="4.291534423828125E-5" order="13"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/15" units-per-pixel="2.1457672119140625E-5" order="14"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/16" units-per-pixel="1.0728836059570312E-5" order="15"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/17" units-per-pixel="5.364418029785156E-6" order="16"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/18" units-per-pixel="2.682209014892578E-6" order="17"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/19" units-per-pixel="1.341104507446289E-6" order="18"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/20" units-per-pixel="6.705522537231445E-7" order="19"/>
<TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/21" units-per-pixel="3.3527612686157227E-7" order="20"/>
</TileSets>
</TileMap>

**Comment by gwaldron** [comment]
right-click and "view page source"...

**Comment by wwwronin** [comment]
<html>
<body>


  | <?xml version="1.0" encoding="UTF-8"?>
-- | --
  |  
  | <TileMap version="1.0.0" tilemapservice="http://localhost:10086/geoserver/gwc/service/tms/1.0.0">
  | <Title>zbaa_15</Title>
  | <Abstract/>
  | <SRS>EPSG:4326</SRS>
  | <BoundingBox minx="90.0" miny="0.0" maxx="135.0" maxy="45.0"/>
  | <Origin x="90.0" y="0.0"/>
  | <TileFormat width="256" height="256" mime-type="image/png" extension="png"/>
  | <TileSets profile="local">
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/1" units-per-pixel="0.3515625" order="0"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/2" units-per-pixel="0.17578125" order="1"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/3" units-per-pixel="0.087890625" order="2"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/4" units-per-pixel="0.0439453125" order="3"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/5" units-per-pixel="0.02197265625" order="4"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/6" units-per-pixel="0.010986328125" order="5"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/7" units-per-pixel="0.0054931640625" order="6"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/8" units-per-pixel="0.00274658203125" order="7"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/9" units-per-pixel="0.001373291015625" order="8"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/10" units-per-pixel="6.866455078125E-4" order="9"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/11" units-per-pixel="3.4332275390625E-4" order="10"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/12" units-per-pixel="1.71661376953125E-4" order="11"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/13" units-per-pixel="8.58306884765625E-5" order="12"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/14" units-per-pixel="4.291534423828125E-5" order="13"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/15" units-per-pixel="2.1457672119140625E-5" order="14"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/16" units-per-pixel="1.0728836059570312E-5" order="15"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/17" units-per-pixel="5.364418029785156E-6" order="16"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/18" units-per-pixel="2.682209014892578E-6" order="17"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/19" units-per-pixel="1.341104507446289E-6" order="18"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/20" units-per-pixel="6.705522537231445E-7" order="19"/>
  | <TileSet href="http://localhost:10086/geoserver/gwc/service/tms/1.0.0/geodb%3Azbaa_15@EPSG%3A4326@png/21" units-per-pixel="3.3527612686157227E-7" order="20"/>
  | </TileSets>
  | </TileMap>


</body>
</html>

**Comment by wwwronin** [comment]
![image](https://github.com/pelicanmapping/rocky/assets/6395346/7c33b083-b556-43ef-a6fd-a635221d5885)

**Comment by gwaldron** [comment]
I do not have a dataset like that to test with, but I attempted to push a fix - give it a try. If it doesn't work we'll log this as a defect and try to reproduce it at some point. Thanks.
