### ISSUE TITLE
Initial Download

### ISSUE THREAD

**Issue by GeorgeRuhlmann** [pelicanmapping/rocky#14]
I downloaded Rocky on 8/23/2023 and starting playing with it.  

Seems very fast.  Looks impressive.  Some issues I ran into include:

1. URI.cpp does not build.   Need to change text httplib::detail::status_message to httplib::status_message.
2. The example rdemo immediately asserts in debug mode.  It asserts in Log::Log because the code is attempting to log an error message before the logger is instantiated.  It is attempting to log an error message because the creation of the global SRS::WGS84 fails.  The global fails because install fails to copy proj.db in the location expected by a debug build.  The release and debug use different paths to locate files.
3. The example rdemo asserts in debug mode, missing ImGui::End() in MainGUI::record.
4. The rdemo quickly goes well over 1GB of memory by just changing view locations.
5. I was getting a lot of crashes, but updating the graphics drive reduced the frequency of the crashes.  Still crashes, just less frequently.

**Comment by gwaldron** [comment]
Thanks for testing George. Points 1, 2, and 3 are hopefully now fixed in the main branch.
Point 4 is a "known issue" and is on the list to work on, I've been putting it off until later.

**Comment by gwaldron** [comment]
Point 4 is now fixed in commit b00927a.
