### ISSUE TITLE
Crash Line String Relative

### ISSUE THREAD

**Issue by GeorgeRuhlmann** [pelicanmapping/rocky#15]
I am using Visual Studio 2022.  I had already turn on/off many features, but when I turned the Line String on for the first time it crashed.  I have not been able to recreate the issue.  See below for a screen shot.

![image](https://github.com/pelicanmapping/rocky/assets/143499428/0038164e-770f-4ae1-8ad6-92016b8182a5)

**Comment by gwaldron** [comment]
I'm not able to reproduce this issue either, and the stack trace in down on VSG. If you see if again, let us know.
