### ISSUE TITLE
Loading Terrain Crash

### ISSUE THREAD

**Issue by GeorgeRuhlmann** [pelicanmapping/rocky#16]
I started rdemo and while still loading the terrain I got a crash.  In the console I see:

Warning: Allocator::MemoryBlock::deallocate(000002238D90D628) problem - couldn't release
Warning: Allocator::MemoryBlock::deallocate(000002238D063F20) problem - couldn't release
Warning: Allocator::MemoryBlock::deallocate(000002238D0078A0) problem - couldn't release
Warning: Allocator::MemoryBlock::deallocate(000002238D064418) problem - couldn't release
Warning: Allocator::MemoryBlock::deallocate(000002238D064038) problem - couldn't release

The stack track show a moves on to itself, which does not look correct (second screen shot).

![image](https://github.com/pelicanmapping/rocky/assets/143499428/30321cfa-734b-4776-9b5f-ad0ac5452ac9)

![image](https://github.com/pelicanmapping/rocky/assets/143499428/38064c35-b307-4bae-97e5-8c866d2ef0f6)
![image](https://github.com/pelicanmapping/rocky/assets/143499428/fb67a685-f1ff-4b4d-bfa5-2dc7d3a3a412)

**Comment by gwaldron** [comment]
Thanks.
I am going to remove the move-constructors from Profile and SRS since they are lightweight objects AND are backed by common globals (and we do not want to move globals). Hopefully that resolves this crash.
