### ISSUE TITLE
Immediate Hang At Start Up

### ISSUE THREAD

**Issue by GeorgeRuhlmann** [pelicanmapping/rocky#17]
I started rdemo and it immediately hanged without any user interaction.  The main thread is stuck in vsg::ThreadSafeQueue<T>::take_when_available().  It never leaves the "while(_queue.empty() && _status->active())" loop.

![image](https://github.com/pelicanmapping/rocky/assets/143499428/a79a388c-041e-402e-a16b-136638ac6227)

**Comment by plevy** [comment]
Do you also get messages in the console:
info: Context::waitForCompletion()  000001A8E3EFEAF0 fence->wait() failed with error. VkResult = -4

I get a hang, not sure it is the same hang as you.  Also, can you check your nVidia control panel 3D settings:
![image](https://github.com/pelicanmapping/rocky/assets/7724641/c6dca80a-f225-4ea8-95b0-4b579cb6e4a7)
If I leave that as Auto, it hangs on startup ( globe appears, imagery appears), and then hangs.  But if I set it to Prefer Native, it doesn't hang.  I think that is a new setting in the driver.

Thank you

**Comment by GeorgeRuhlmann** [comment]
It only hanged once and I do not remember if there was any console output.    I have changed the driver setting to "Prefer native".  It might be a couple weeks before I get back to this.
