### ISSUE TITLE
random crash in rocky while zooming and panning

### ISSUE THREAD

**Issue by keince** [pelicanmapping/rocky#19]
While running `rocky`, I'm noticing a random crash while panning around on the Earth (see attached image below on details).

I'm seeing this running the `rdemo.exe` and `rengine.exe` apps. It appears to happen at different times during execution but it happens regularly at the same location in the code (vsg).

My environment...
OS:                  Windows 10
IDE:                  Visual Studio 2022
Configuration: RelWithDebInfo
Platform:          x64

![RockyCrashCapture](https://github.com/pelicanmapping/rocky/assets/80072561/dfc71eb3-fb90-444f-ac4c-f9ec0a476690)

**Comment by keince** [comment]
Just a follow-up to my previous post,.. 

I'm noticing that the process memory (in the diagnostic tools) steadily increases as I move around until it reaches 10.1+ Gb. It is at this point that the crash occurs. 

It's like memory isn't being released somewhere...

**Comment by gwaldron** [comment]
Yes. I have noticed the same thing, and it seems to be a function of the pre-allocation of pools in ResourceHints.

In rengine.cpp we are using those resource hints and there's a big memory leak. In rdemo (the code is actually in Application.cpp line ~564)  however we're limiting the numDescriptorSets to 1, and there problem doesn't exist.

I am not smart enough about the guts of VSG (yet?) to know what's up, so I appreciate the experimentation and sharing of knowledge :)

**Comment by keince** [comment]
Thanks for the feedback Glenn.

For the record, the crash still occurs with `rdemo.exe`  like the other applications. 

Looking at my version, it has `resourceHints->numDescriptorSets = 64;` for line 564.

I will do some further research and investigation on the matter on my end to try and help...

**Comment by gwaldron** [comment]
Grab the latest (with numDescriptorSets = 1) and let me know if you still se the problem.

**Comment by keince** [comment]
Okay.

I did a pull of the `rocky` repo.

Do I need to rerun the `bootstrap-vcpkg.bat` file to update?

**Comment by gwaldron** [comment]
Probably not, but I would definitely re-run cmake on your build folder.

**Comment by keince** [comment]
I was finally able to run the `rsimple.exe` application with the aforementioned changes to the `numDescriptorSets` and the crash has not happened yet.

However, now I'm seeing something different. It appears that paging stalls periodically so that the higher LODs don't page in.
I've attached a picture showing the problem.
![RockyPagingCapture](https://github.com/pelicanmapping/rocky/assets/80072561/4741b294-25ee-4994-be27-a856a4235645)

**Comment by gwaldron** [comment]
Can you give me the viewpoint?
In rdemo, open Camera->Viewpoints and take a screenshot.

**Comment by keince** [comment]
Here's a capture around the same area with viewpoint displayed. It might be the source imagery for the tile but I don't see this in osgEarth using ReadyMap...

![RockyPagingCapture2](https://github.com/pelicanmapping/rocky/assets/80072561/b035244e-dca5-4210-a19b-d97b6e6d0e6d)

**Comment by keince** [comment]
Glenn,
 
Not sure if this is related but I'm noticing that rengine.exe won't render the ReadyMap tiles with the latest git pull of rocky. I just see an orange globe.
 
Do you see this as well?
 
I debugged into the rengine.cpp and it appears to be loading the imagery and elevation layers okay.
 
I'm able to run rdemo.exe and rsimple.exe and see the ReadyMap stuff fine so it's not a network problem on my end.
 
Shayne

**Comment by gwaldron** [comment]
It's just missing data on the server. (This is osgEarth, Rocky, and ReadyMap console from left to right)

<img width="1746" alt="image" src="https://github.com/pelicanmapping/rocky/assets/326618/290be834-2c54-4d83-bcd8-63871b6a2587">

**Comment by gwaldron** [comment]
As for rengine, I pushed a quick fix for that -- I would stick to rdemo for the most part since that's the app that gets the most attention. I do not spend as much time keeping the other 2 up to date :)
