### ISSUE TITLE
"The ordinal 125 could not be located in... gdlad.dll"

### ISSUE THREAD

**Issue by fkane** [pelicanmapping/rocky#24]
I probably did something dumb, but having a hard time getting rdemo.exe to run successfully.

- cloned the latest rocky repo from github
- ran bootstrap-vcpkg.bat successfully (after a few retries due to Visual Studio 2022's compiler crashing sporadically)
- built the debug target and set the required environment variables
- ran rdemo.exe from the install/bin directory

This results in a popup at startup saying "The ordinal 125 could not be located in the dynamic link library e:\rocky\install\bin\gdlad.dll"

Is this a bad dependency, or did I mess up?

**Comment by jasonbeverage** [comment]
Hey Frank, try building the RelWithDebInfo target instead and see if that works.  If you ran bootstrap.vcpkg it's setting the build type to RelWithDebInfo so it's picking up release dependencies and not debug.  I think if you build in debug you'll need to change the bootstrap script to Debug and use a separate directory from your release build.  Give that a shot and see if you have any luck.

**Comment by fkane** [comment]
Hm, now it's complaining about non-debug DLL's not being present in the install/bin directory I'm running from (like gdal.dll.) That's why I went straight to Debug.

Something must have gotten horked during the build process; I'll try starting again from scratch.

**Comment by jasonbeverage** [comment]
In your build directory there will also be a directory called vcpkg_installed.   You need to add the vcpkg_installed\bin directory to your path.

**Comment by fkane** [comment]
Ah! Might want to include that step in the build instructions (as well as a reminder to only build RelWIthDebInfo)

That got me further, but now it's complaining about the sqlite3_column_table_name entry point not being located within gdal.dll within the build\vcpkg_installed\x64-windows\bin directory I added to the path.

I guess I'll tackle this again in a bit; we can probably close this issue though as it's drifted pretty far from the original problem now.

**Comment by fkane** [comment]
Got the rocky-demo project working after including build\vcpkg_installed\x64-windows\bin in the path. All good! Thanks.
