### ISSUE TITLE
error: building pkgconf:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Bj29ASH** [pelicanmapping/rocky#27]
1. Clone the rocky repo.
2. Installed vcpkg
3. Installed Vulkan SDK
4. ran bootstrap.bat

Getting the following error:

CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/pkgconf/portfile.cmake:79 (vcpkg_copy_tools)
  scripts/ports.cmake:175 (include)

error: building pkgconf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle pkgconf:x64-windows: 11 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+pkgconf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[pkgconf]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2FWorkspace%2Fother%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at D:/Workspace/other/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  D:\Workspace\other\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:11 (project)

-- Configuring incomplete, errors occurred!

**Comment by gwaldron** [comment]
Unfortunately sometimes vcpkg ports break. There's not a lot one can do about it besides (a) reverting to an older commit of your vcpkg installation; or (b) waiting until they fix the offending portfile. Sorry for the trouble :)
