### ISSUE TITLE
Error: Did you set ROCKY_FILE_PATH to point at the rocky share folder?

### ISSUE THREAD

**Issue by shujaatak** [pelicanmapping/rocky#5]
### **Issue I am facing:**

I get the following error when running **rsimple.exe**, I can't also run rdemo.exe and rengine.exe.:
```
FATAL ASSERTION FAILURE (InstanceVSG @ InstanceVSG.cpp:190) Line shaders are missing or corrupt. Did you set ROCKY_FILE_PATH to point at the rocky share folder?
```

### **How I have built the project and setup the paths:**

I have followed the build steps mentioned in the **Readme** file, I have got the following files in the **build->bin->Release** folder:

![image](https://github.com/pelicanmapping/rocky/assets/14161646/d83d850e-026d-4620-92cb-19d2c51a2ac1)

I have set the **ROCKY_FILE_PATH** to the **share** folder in **build->bin->Release** as shown above in the snapshot.
The **share** folder had nothing in it so I copied **shaders** folder from **rocky/src/rocky_vsg/** to **build->bin->Release->share**.

Similarly, I have set **PROJ_DATA** to **build->bin->Release->proj** but **proj** directory is also empty and I don't know what to copy in it.

And I have set **ROCKY_DEFAULT_FONT** to **C:/windows/fonts/arialbd.ttf**

**Comment by plevy** [comment]
Are you running bootstrap-vcpkg.bat?  That should be setting an install folder where you would find the binaries and the share folder

**Comment by shujaatak** [comment]
Yes, I am running **bootstrap-vcpkg.bat** from **rocky** repository.

**Comment by shujaatak** [comment]
I get only **build** directory containing the following content:

![image](https://github.com/pelicanmapping/rocky/assets/14161646/229b1ebe-8c70-4f14-bfd2-8c94132587fe)

**Comment by shujaatak** [comment]
Finally I got the projects to run but this involved some manual work (**I am still waiting for the official proper build procedure**)

I set the **ROCKY_FILE_PATH** environment variable to the **build->bin->Release->share** folder.
And I copied **shaders** folder from **rocky/src/rocky_vsg/** to **build->bin->Release->share** folder.

Similarly, I set the **PROJ_DATA** environment variable to the **build->bin->Release->proj** folder.
And I copied **proj.db** from **build/vcpkg_installed/x64-windows/share/proj** to  **build->bin->Release->proj** folder.

I set **ROCKY_DEFAULT_FONT** environment variable to **C:/windows/fonts/arialbd.ttf**

**NOTE:** If you are building and running the project using **Visual Studio**, you need to **_restart_** Visual Studio whenever you add or remove Environment Variables!

![image](https://github.com/pelicanmapping/rocky/assets/14161646/93a254c5-43ca-460c-92e2-086885aa0385)

**Comment by gwaldron** [comment]
Glad you got it working.
The "official" thing to do is to build the INSTALL project in Visual Studio - this will install all the headers, shaders, and executables to the install folder you designated when you `bootstrap-vcpkg.bat`.
