### ISSUE TITLE
Cannot Run Rocky from Visual Studio to debug problems

### ISSUE THREAD

**Issue by bclay1297** [pelicanmapping/rocky#56]
Getting back to rocky after other conflicts.  I still cannot get things working with.  When try to build Rocky using Visual Studio IDE Build capabilities I get numerous warnings that look like they could cause trouble and when I try  to run Any of the apps they crash immediately with an error "the procedure entry point getLayerTypeName@Layer@rockyimmediately....

The project builds without errors and I can run for a short time from the command line but after a few seconds it freezes.  Then it crashes not stack trace is shown in visual studio.

I get several warnings about #if VSG_API_VERSION_LESS(1, 1, 7) the warning shown is
   warning C4067: unexpected tokens following preprocessor directive - expected a newline
This I suspect is a non-issue

The other warnings appear to be more important.  I turned on Visual Studio code analysis to try to dig out more information so they may be related to that.

3>Generating Code...
3>rdemo.vcxproj -> G:\build\src\apps\rdemo\Debug\rdemo.exe
G:\build\vcpkg_installed\x64-windows\include\fmt\core.h(402): warning C6285: (<non-zero constant> || <non-zero constant>) is always a non-zero constant.  Did you intend to use the bitwise-and operator?
G:\build\vcpkg_installed\x64-windows\include\vsg\utils\Instrumentation.h(88): warning C26495: Variable 'vsg::CpuInstrumentation::reference' is uninitialized. Always initialize a member variable (type.6).
G:\build\vcpkg_installed\x64-windows\include\vsg\utils\Instrumentation.h(107): warning C26495: Variable 'vsg::GpuInstrumentation::reference' is uninitialized. Always initialize a member variable (type.6).
G:\build\vcpkg_installed\x64-windows\include\vsg\utils\Instrumentation.h(125): warning C26495: Variable 'vsg::CommandBufferInstrumentation::reference' is uninitialized. Always initialize a member variable (type.6).
G:\rocky\src\rocky\SRS.h(278): warning C26439: This kind of function should not throw. Declare it 'noexcept' (f.6).
G:\rocky\src\rocky\GeoPoint.h(85): warning C26439: This kind of function should not throw. Declare it 'noexcept' (f.6).
G:\rocky\src\rocky\GeoExtent.h(25): warning C26439: This kind of function should not throw. Declare it 'noexcept' (f.6).
G:\rocky\src\rocky\Image.h(183): warning C26495: Variable 'rocky::Image::iterator::_s' is uninitialized. Always initialize a member variable (type.6).
G:\build\vcpkg_installed\x64-windows\include\vsg\state\BindDescriptorSet.h(160): warning C26495: Variable 'vsg::BindDescriptorSet::VulkanData::_vkDescriptorSet' is uninitialized. Always initialize a member variable (type.6).
G:\rocky\src\rocky\vsg\MapManipulator.h(179): warning C26495: Variable 'rocky::MapManipulator::ActionOption::<unnamed-tag>::intValue' is uninitialized. Always initialize a member variable (type.6).
G:\rocky\src\rocky\vsg\MapManipulator.h(721): warning C26495: Variable 'rocky::MapManipulator::State::setVPArcHeight' is uninitialized. Always initialize a member variable (type.6).
G:\rocky\src\rocky\GeoImage.h(28): warning C26439: This kind of function should not throw. Declare it 'noexcept' (f.6).
G:\rocky\src\rocky\GeoHeightfield.h(25): warning C26439: This kind of function should not throw. Declare it 'noexcept' (f.6).
G:\rocky\src\apps\rdemo\Demo_Tethering.h(62): warning C6385: Reading invalid data from 'indices'.
G:\build\vcpkg_installed\x64-windows\include\vsg\ui\TouchEvent.h(26): warning C26495: Variable 'vsg::TouchEvent::x' is uninitialized. Always initialize a member variable (type.6).
G:\rocky\src\rocky\Math.h(410): warning C6295: Ill-defined for-loop.  Loop executes infinitely.
G:\build\vcpkg_installed\x64-windows\include\entt\core\enum.hpp(46): warning C26827: Did you forget to initialize an enum constant, or intend to use another type?.
G:\rocky\src\rocky\vsg\ECS.h(335): warning C26495: Variable 'rocky::Motion::acceleration' is uninitialized. Always initialize a member variable (type.6).
G:\build\vcpkg_installed\x64-windows\include\fmt\format.h(2842): warning C26498: The function 'fmt::v10::detail::num_bits<unsigned __int64>' is constexpr, mark variable 'shift' constexpr if compile-time evaluation is desired (con.5).
3>Done building project "rdemo.vcxproj".
========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========

One of the messages my account for the freeze issue.  Math.h at line 410
                for (unsigned int i = length * size_t_bits; i > 0; i -= size_t_bits)
G:\rocky\src\rocky\Math.h(410): warning C6295: Ill-defined for-loop.  Loop executes infinitely.

I am working on Windows 10 using Visual Studio 2022.  I download the Rock source 2 days ago uisng the supplied batch file.

Bruce

**Comment by gwaldron** [comment]
Hi Bruce. We've not seen these issues, but if I had to guess, I would suspect that somehow your compiler is trying to use C++20 (or some other language constraint) to build the SDK, or is configured to use unusually strict compilation warnings. Just a guess, as I'm unsure how that would occur when using the stock CMake and vcpkg setup. I'm current on travel but will try to assist more next week.
