### ISSUE TITLE
clang (XCode 14) compile errors 

### ISSUE THREAD

**Issue by remoe** [pelicanmapping/rocky#7]
### 1

`Error: "Incomplete type 'rocky::util::job_scheduler' named in nested name specifier" at job_scheduler::Delegate delegate = [task, promise]() mutable ...
`
https://github.com/pelicanmapping/rocky/blob/main/src/rocky/Threading.h#L488

because 

https://github.com/pelicanmapping/rocky/blob/main/src/rocky/Threading.h#L572

"using Delegate" is not forward declared and can't be forward declared:

https://github.com/pelicanmapping/rocky/blob/main/src/rocky/Threading.h#L397

### 2

`Error: Use of undeclared identifier 'options'`

     template<typename T>
     T Layer::userProperty(const std::string& key, T fallback) const {
        return options()._internal().value(key, fallback);
     }

### 3

rocky/srs.h

`static const SRS WGS84; 
`
`Error: duplicated member WGS84`

need to delete:

```
        static const SRS WGS84;
        static const SRS ECEF;
        static const SRS SPHERICAL_MERCATOR;
        static const SRS PLATE_CARREE;
        static const SRS EMPTY;

```

SRS& SRS::operator=(SRS&&);

`Error: extra qualification on member 'operator='`

need to change:

`SRS& operator=(SRS&&);``

### 4

rocky/Heightfield.h

```
     template<typename FUNC>
     void Heightfield::forEachHeight(FUNC func) const
     {
-        float* ptr = data<float>();
+        const float* ptr = data<float>();
         for (auto i = 0u; i < sizeInPixels(); ++i, ++ptr)
             func(*ptr);
     }

```

### 5

rocky/Image.h

```
     template<typename UV_TYPE, typename ST_TYPE>
     void Image::nnUVtoST(UV_TYPE u, UV_TYPE v, ST_TYPE& s, ST_TYPE& t)
     {
-        const UV_TYPE umin = 1.0 / (2.0 * width);
-        const UV_TYPE vmin = 1.0 / (2.0 * height);
-        s = u<umin ? 0 : u>(1.0 - umin) ? width - 1 : (int)floor(u*(double)width);
-        t = v<vmin ? 0 : v>(1.0 - vmin) ? height - 1 : (int)floor(v*(double)height);
+        const UV_TYPE umin = 1.0 / (2.0 * width());
+        const UV_TYPE vmin = 1.0 / (2.0 * height());
+        s = u<umin ? 0 : u>(1.0 - umin) ? width() - 1 : (int)floor(u*(double)width());
+        t = v<vmin ? 0 : v>(1.0 - vmin) ? height() - 1 : (int)floor(v*(double)height());
 
     }

```

### 6

rocky/IOTypes.h

```
        bool fromCache = false;
        JSON metadata;

-       template<typename T>
        IOResult(const T& result) :
            Result<T>(result) { }

```

For this I can't do a PR. I will try to compile it further after the issues are fixed ...

**Comment by gwaldron** [comment]
Thanks Remo! All are fixed.

**Comment by remoe** [comment]
The code has compile issues in LayerCollection.h. The forward declare of Map:

https://github.com/pelicanmapping/rocky/blob/main/src/rocky/LayerCollection.h#L13

can't work with the following template implementation:

https://github.com/pelicanmapping/rocky/blob/main/src/rocky/LayerCollection.h#L88

And it doesn't compile with `#include <rocky/Map.h>` .

**Comment by remoe** [comment]
The `job `and `job_scheduler` class must be separated, because of circular dependencies? Or should at least the `job::dispatch` implementation be moved to `Threading.cpp`?

**Comment by gwaldron** [comment]
Remo, I feel like many of these issues are just templates being instantiated before they are used. Is there some king of clang option for this? Because it isn't a problem on MSVC. Don't know about GCC.

**Comment by remoe** [comment]
I haven't found a clang option to configure template instancing. Currently, I'm able to compile the project with my additional PR. But it need more work to link and run it.
